"""Add imagen_url to Producto

Revision ID: 6b04a2f0e9b0
Revises: 7274010943ee
Create Date: 2026-10-05 11:57:51.599360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b04a2f0e9b0'
down_revision: Union[str, Sequence[str], None] = '7274010943ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_url')
    # ### end Alembic commands ###
