"""Add SolicitudRevocacion

Revision ID: 7274010943ee
Revises: b06ba7ef6f5a
Create Date: 2026-10-05 10:34:02.638105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7274010943ee'
down_revision: Union[str, Sequence[str], None] = 'b06ba7ef6f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_revocacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_revocacion_codigo'), 'solicitudes_revocacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_solicitudes_revocacion_id'), 'solicitudes_revocacion', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_baja', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_baja')
    op.drop_column('usuarios', 'activo')
    op.drop_index(op.f('ix_solicitudes_revocacion_id'), table_name='solicitudes_revocacion')
    op.drop_index(op.f('ix_solicitudes_revocacion_codigo'), table_name='solicitudes_revocacion')
    op.drop_table('solicitudes_revocacion')
    # ### end Alembic commands ###
