"""usuarios con auth

Revision ID: b06ba7ef6f5a
Revises: b35a4db9cd57
Create Date: 2026-09-22 13:19:45.140333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06ba7ef6f5a'
down_revision: Union[str, Sequence[str], None] = 'b35a4db9cd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('rol', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
