"""campos frontend en producto

Revision ID: b35a4db9cd57
Revises: 1ea93db3d2d2
Create Date: 2026-09-22 13:07:32.680905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35a4db9cd57'
down_revision: Union[str, Sequence[str], None] = '1ea93db3d2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precio_final', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('productos', sa.Column('cuotas_cantidad', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('cuotas_valor', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('productos', sa.Column('garantia_meses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'garantia_meses')
    op.drop_column('productos', 'cuotas_valor')
    op.drop_column('productos', 'cuotas_cantidad')
    op.drop_column('productos', 'precio_final')
    # ### end Alembic commands ###
